const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs/promises');
const {pathToFileURL}=require('node:url');
const inRepo=require('node:fs').existsSync(path.resolve(__dirname,'../../../lib/Noosphere/ComputationalResources.pm'));
const file=process.env.VIEWER_FILE||path.resolve(__dirname,inRepo?'../../../data/examples/em-field-lab/index.html':'../index.html');
const output=path.resolve(__dirname,'../qa');
const executablePath=process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
async function field(page,id,value){await page.locator('#'+id).evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));}
async function pixels(page){return page.evaluate(async()=>{await new Promise(requestAnimationFrame);const canvas=document.querySelector('#scene canvas'),gl=canvas.getContext('webgl2'),data=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,data);let gold=0,cyan=0,bright=0,signature=0;for(let j=0;j<data.length;j+=4){const r=data[j],g=data[j+1],b=data[j+2];if(r>100&&r>g*1.05&&g>b*1.4)gold++;if(b>100&&b>r*1.3&&g>r*1.2)cyan++;if(Math.max(r,g,b)>100)bright++;if(j%64===0)signature=(signature+r*7+g*11+b*13)%1000000007;}return {gold,cyan,bright,signature};});}
async function layout(page){return page.evaluate(()=>{const visible=el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden';const bad=[...document.querySelectorAll('button,label,h1,.wave-summary,.probe-readouts dd,.directions dd')].filter(visible).filter(el=>el.scrollWidth>el.clientWidth+1).map(el=>el.id||el.className||el.tagName);return {overflow:document.documentElement.scrollWidth>innerWidth+1,bad};});}
(async()=>{
  await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath});
  try{
    const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1}),errors=[],remote=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
    await page.goto(pathToFileURL(file).href);await page.waitForFunction(()=>document.querySelector('#a-psi').textContent.length);await page.waitForTimeout(300);
    assert.equal(await page.locator('#webgl-fallback').isVisible(),false);const first=await pixels(page);assert.ok(first.gold>100&&first.cyan>100,JSON.stringify(first));assert.deepEqual(await layout(page),{overflow:false,bad:[]});
    await page.screenshot({path:path.join(output,'desktop-vector.png'),fullPage:true});
    const profile=await page.locator('.snapshot-path').getAttribute('d'),trace=await page.locator('.history-a').getAttribute('d'),position=await page.locator('#a-position').textContent();
    await page.locator('#camera-xy').click();await page.waitForTimeout(200);assert.notEqual((await pixels(page)).signature,first.signature);assert.equal(await page.locator('.snapshot-path').getAttribute('d'),profile);assert.equal(await page.locator('.history-a').getAttribute('d'),trace);await page.locator('#camera-reset').click();
    await page.locator('#play').click();await page.waitForTimeout(600);assert.ok(+await page.locator('#time').inputValue()>0);assert.notEqual((await pixels(page)).signature,first.signature);assert.notEqual(await page.locator('.snapshot-path').getAttribute('d'),profile);assert.equal(await page.locator('#a-position').textContent(),position);assert.equal(await page.locator('.history-a').getAttribute('d'),trace);await page.locator('#play').click();
    await field(page,'time',.5);assert.equal(await page.locator('#a-psi').textContent(),'-5.000');assert.equal(await page.locator('#a-magnitude').textContent(),'5.000');assert.match(await page.locator('#a-vector').textContent(),/-5.000/);
    await page.locator('#quantity').selectOption('magnitude');assert.match(await page.locator('#quantity-note').textContent(),/nonnegative/);await page.locator('#history').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#time-value').textContent(),'0.000');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#time-value').textContent(),'0.010');
    const box=await page.locator('#history').boundingBox();await page.mouse.click(box.x+box.width*.75,box.y+80);assert.ok(+await page.locator('#time').inputValue()>1.3);await page.locator('#reset-time').click();assert.equal(await page.locator('#time-value').textContent(),'0.000');
    await page.locator('#preset').selectOption('oblique');await page.locator('#quantity').selectOption('psi');await page.locator('#scalar-tab').click();assert.equal(await page.locator('#slice').isVisible(),true);assert.ok((await pixels(page)).bright>1000);await field(page,'slice',.7);await page.screenshot({path:path.join(output,'desktop-scalar.png'),fullPage:true});const scalar=await pixels(page);await field(page,'time',.4);assert.notEqual((await pixels(page)).signature,scalar.signature);
    await page.locator('#scalar-tab').focus();await page.keyboard.press('End');assert.equal(await page.locator('#vector-tab').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#slice').isVisible(),false);
    await page.locator('#preset').selectOption('article');await field(page,'spacing',1);assert.match(await page.locator('#delay-readout').textContent(),/phase lag 0.0/);assert.equal(await page.locator('.history-a').getAttribute('d'),await page.locator('.history-b').getAttribute('d'));await field(page,'spacing',0);assert.equal(await page.locator('#a-position').textContent(),await page.locator('#b-position').textContent());
    await page.locator('#preset').selectOption('rotated');await page.locator('#quantity').selectOption('ey');assert.equal(await page.locator('#a-vector').textContent(),'(0.000, 5.000, 0.000)');await page.locator('#preset').selectOption('reverse');assert.match(await page.locator('#n-vector').textContent(),/-1.000/);assert.equal(await page.locator('#a-vector').textContent(),'(5.000, 0.000, 0.000)');
    await page.locator('#preset').selectOption('article');await page.locator('#quantity').selectOption('psi');const before=await page.locator('.history-a').getAttribute('d'),metres=await page.locator('#b-metres').textContent();await field(page,'frequency',2000);assert.equal(await page.locator('.history-a').getAttribute('d'),before);assert.notEqual(await page.locator('#b-metres').textContent(),metres);assert.equal(await page.locator('#period-readout').textContent(),'0.500 ns');
    await field(page,'frequency',0);assert.equal(await page.locator('#input-error').isVisible(),true);assert.equal(await page.locator('#frequency-readout').textContent(),'2000.00 MHz');await field(page,'frequency-log',2);assert.equal(await page.locator('#input-error').isVisible(),false);assert.equal(await page.locator('#frequency-readout').textContent(),'100.00 MHz');
    await page.locator('#preset').selectOption('gps');assert.equal(await page.locator('#wavelength-readout').textContent(),'0.1903 m');await page.locator('#preset').selectOption('zero');assert.equal(await page.locator('#a-psi').textContent(),'0.000');assert.equal(await page.locator('#a-magnitude').textContent(),'0.000');assert.ok((await pixels(page)).gold<10);assert.ok(!/NaN|Infinity/.test(await page.locator('.workspace').textContent()));
    await page.locator('#preset').selectOption('reverse');await page.locator('#snapshot').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#z').inputValue(),'-0.01');await page.locator('#snapshot').focus();await page.keyboard.press('End');assert.equal(await page.locator('#z').inputValue(),'-0.5');
    await page.locator('#preset').selectOption('article');const event=page.waitForEvent('download');await page.locator('#export').click();const download=await event;assert.equal(download.suggestedFilename(),'em-field-probe-histories.csv');assert.match(await fs.readFile(await download.path(),'utf8'),/time_s,x_m,y_m,z_m/);
    for(const [width,height] of [[768,1024],[390,844],[320,900]]){
      await page.setViewportSize({width,height});await page.waitForTimeout(250);assert.deepEqual(await layout(page),{overflow:false,bad:[]});const px=await pixels(page);assert.ok(px.gold>50&&px.cyan>50,JSON.stringify(px));await page.screenshot({path:path.join(output,`vector-${width}.png`),fullPage:true});
      await page.locator('#preset').selectOption('oblique');await page.locator('#scalar-tab').click();await page.waitForTimeout(100);assert.deepEqual(await layout(page),{overflow:false,bad:[]});assert.ok((await pixels(page)).bright>500);await page.screenshot({path:path.join(output,`scalar-${width}.png`),fullPage:true});await page.locator('#vector-tab').click();await page.locator('#preset').selectOption('article');
    }
    assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
    const fallback=await browser.newPage({viewport:{width:390,height:844}}),fallbackErrors=[];fallback.on('pageerror',e=>fallbackErrors.push(e.message));await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /^webgl/.test(type)?null:original.call(this,type,...args);};});await fallback.goto(pathToFileURL(file).href);await fallback.waitForFunction(()=>document.querySelector('#a-psi').textContent.length);assert.equal(await fallback.locator('#webgl-fallback').isVisible(),true);await field(fallback,'time',.5);assert.equal(await fallback.locator('#a-psi').textContent(),'-5.000');await fallback.locator('#scalar-tab').click();assert.deepEqual(fallbackErrors,[]);
    console.log('Browser QA passed: desktop/tablet/mobile, WebGL colors and motion, camera independence, fixed probes, signed field/magnitude, scalar/vector views, snapshot/history, delay ambiguity, physical units, validation, CSV export, offline assets and WebGL fallback.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
